apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  labels:
    app: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image:  igorvlima/order_api:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "${SPRING_DATASOURCE_URL}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "${SPRING_DATASOURCE_USERNAME}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "${SPRING_DATASOURCE_PASSWORD}"
            - name: CUSTOMER_API_URL
              value: "${CUSTOMER_API_URL}"
            - name: PRODUCT_API_URL
              value: "${PRODUCT_API_URL}"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
